### ISSUE TITLE
Verify assumption: community pool assets are created by the fees from the machine TXs

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint-go#103]

**Comment by jmastr** [comment]
- The community pool gets `community_tax * fees`, plus any remaining dust after validators get their rewards that are always rounded down to the nearest integer value. https://docs.cosmos.network/main/build/modules/distribution#reward-to-the-community-pool
- A delegator can withdraw its rewards. Internally in the distribution module, this transaction simultaneously removes the previous delegation with associated rewards, the same as if the delegator simply started a new delegation of the same value. The rewards are sent immediately from the distribution ModuleAccount to the withdraw address. Any remainder (truncated decimals) are sent to the community pool. https://docs.cosmos.network/main/build/modules/distribution#msgwithdrawdelegatorreward
- FundCommunityPool: This message sends coins directly from the sender to the community pool. https://docs.cosmos.network/main/build/modules/distribution#fundcommunitypool
- Validator removed: Outstanding commission is sent to the validator's self-delegation withdrawal address. Remaining delegator rewards get sent to the community fee pool. https://docs.cosmos.network/main/build/modules/distribution#validator-removed
