### ISSUE TITLE
add tx hash to MintRequest

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint-go#132]
## Description
For better visibility on chain the tx hash should be added to the MintRequest stored in the DaoKeeper. It is not available in the msg server. We need to figure out how to get this before being stored to the DB

**Comment by eckelj** [comment]
The tx-hash exists at

https://github.com/planetmint/planetmint-go/blob/f6a7a567042601c9a95396b6a779929c95df3561/proto/planetmintgo/dao/mint_request.proto#L10

and is also stored in a key value store. 
or does this ticket refer to something else?

**Comment by eckelj** [comment]
@eckelj & @LaurentMontBlanc had a discussion and identified that the planetmint TxID was actually meant. 
this cannot be easily done without ANTI handler & message server/keeper intreaction. We see that this or such a feature should be provided by an explorer. or an extention of an explorer.
