### ISSUE TITLE
POP Participant Election

### ISSUE THREAD

**Issue by GR3G0RYO** [planetmint/planetmint-go#217]
In abci.go, the block proposer has to select the PoP Participants (challenger, challengee). We have to make a selection of who is to be part of the upcoming PoP.
The funds will be transferred to the PoPAccount on liquid if none are elected, but no claims will be assigned (default behaviour <- this should already be in place, to be verified).

**Comment by LaurentMontBlanc** [comment]
Election: Iterate incrementally over account numbers and check if address is machine. Select 2 machines and store the last account number that was used for election or check from last election account number. If end of account numbers reached start with 0 again.
