### ISSUE TITLE
Reduce test pipeline time by switching from explicit to implicit testing

### ISSUE THREAD

**Issue by jmastr** [planetmint/planetmint-go#284]
Our system does things implicitly. Namely:

- sending PoPs every two minutes
- reissue the RDDL token once a day on liquid
- distribute said liquid token half an hour later two the investor, dao and pop wallet

Taking the reissuance for example. At on point we explicitly send a `daotypes.NewMsgReissueRDDLProposal` message explicitly and at another point we set `conf.ReissuanceEpochs` and wait til the reissuance is send implicitly.

The explicit test cases were created at a point at which we did not have the implicit behavior yet. However the implicit behavior is how the system functions when deployed and running. Thus I'd suggest to remove all the explicit test cases and replace them if not already happened by implicit ones.

**Comment by GR3G0RYO** [comment]
Needed Discussion on way forward with different options available to us

**Comment by eckelj** [comment]
I did so for the pop tests. Let's discuss what is to be expected here and write it down so that we avoid misunderstandings.

**Comment by eckelj** [comment]
We must define what tests should be rewritten into implicit tests without explicit manipulation.

**Comment by eckelj** [comment]
Closed as we fixed this implicitly before.
