### ISSUE TITLE
Connect SSS-Wallets to DAO and PoP Wallet workflows

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint-go#302]
- [ ] Connect the DAO wallet Coordinator to the Validator Funding 
- [ ] Connect the PoP Wallet Coordinator to the Claim-Redeem-Service

* 1st implementation on via trezor-code (https://github.com/trezor/python-shamir-mnemonic)
* coordinator service (aggregate and distribute secrets 
* share-holder service (store secret and send secret to coordinator)

1st iteration: signing only (without criteria validation)
2nd iteration: signing and sharing after validation of signing criteria

**Comment by jmastr** [comment]
Here is a small Go wrapper around trezor's shamir.c: https://github.com/jmastr/trezor-shamir-go

**Comment by eckelj** [comment]
taken care of by https://app.zenhub.com/workspaces/rddl-network-6290b7d7a16747001d0c48bf/issues/gh/rddl-network/ansible/33
