### ISSUE TITLE
[bug] asset query does not repsect lookupPeriodInMin value

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint-go#402]
<img width="990" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnNXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7bda73a7757a68fb44ac2d3e481d98e57f61002f/image.png" alt="image.png" />

The assert query for assets of a given address does not respect the LookupPeriodInMin value. 
As a result, rddl-Tasmota devices crash due to the lack of memory to process the response.

e.g.: planetmint-god query asset address plmnt1z6xmwqfnn9mvean9gsd57segawgjykpxw8hq5t 4

**Comment by LaurentMontBlanc** [comment]
Approach:
- [ ] add timestamp to NotarizeAssetMsg
- [ ] add AssetKey function that respects timestamp
- [ ] update StoreAsset
- [ ] update GetAsset
- [ ] add storemigration
