### ISSUE TITLE
websocket connection error 

### ISSUE THREAD

**Issue by eckelj** [planetmint/planetmint-go#452]
Sep 30 04:59:21 ip-10-21-18-216 planetmint-god[1691359]: #033[90m4:59AM#033[0m #033[1m#033[31mERR#033[0m#033[0m Failed to read request #033[36merr=#033[0m"websocket: close 1001 (going away)" #033[36mmodule=#033[0mrpc-server #033[36mprotocol=#033[0mwebsocket #033[36mremote=#033[0m127.0.0.1:59136

Sep 30 04:59:21 ip-10-21-18-216 planetmint-god[1691359]: #033[90m4:59AM#033[0m #033[1m#033[31mERR#033[0m#033[0m error while stopping connection #033[36merror=#033[0m#033[31m"already stopped"#033[0m #033[36mmodule=#033[0mrpc-server #033[36mprotocol=#033[0mwebsocket

**Comment by GR3G0RYO** [comment]
Planetmint go websocket email alerts

Happens when the pipeline runs 

Fix needs to be investigated

**Comment by eckelj** [comment]
I don't think that we can remove this error. even if we take down and restart one node after the other will result in the:
the remaining nodes will report that the node being updated is offline. it's a legit error message. during upgrade or restart.

**Comment by jmastr** [comment]
I did not know that we had a ticket for that. i added logcheck ignore rules some days ago. these message also appeared during normal operation, but i think it is nothing we can act on. the software tries to reconnect to the rpc automatically... i think the issue can be closed.
