### ISSUE TITLE
concept for liquid/planetmint-go proof service

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint-go#6]
A tx needs to be triggered on planetmint-go based on a master seed (mnemonic phrase) where a eduards curve and weierstras curve are derivated. Proofs that tx on liquid and planetmint was issued by the same entity

- [x] Add manual to doc.rddl.io how to verify if two keys are correlated via API

**Comment by eckelj** [comment]
The planetmint and liquid keys are derived from one seed but with different hardened derivation paths. Both keys, thus don't originate from the same public key and can therefore not be compared.

The extended public keys are notarized during the machine attestation process. That's where the liquid-to-planemint relation of keys is notarized and stored. That's where the match can be verified. The machine itself can be challenged to proof key ownership in both cases.

**Comment by eckelj** [comment]
We could create a validation mechanism for both keys or a challenge-response command on the Tasmota. this would solve the issue and give transparency.

**Comment by eckelj** [comment]
Here is the manual on how to verify if two pub keys belong to each other:
https://docs.rddl.io/rddl-network/basics/types-of-nodes/key-ceremony#tasmota-nodes
